# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18128e27d49c27294f1a10426fc77e16cd9645728d2bbab73817ac1a0c923b377cb41a8ef18d4cbf7a0e4d64700718a4ed0de0f9f2553d8b3bc64cb2e4780fd1

test:
  secret_key_base: 95115892df6a6ab7328a999d98c9e0a09ba6153cccdef5286aeaad733495f42d87a53bf11b6b941730bef348e876654668dc13333d958bacacd9f9b8b3b136ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
