# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2095772d88b70cf3b624aad44a73ca0f497e5c86fa471e6e7e67f712c3c17b0455e1fc85586829bade278e00a315765ae72d419f9efb9464bff111e33f7974cc

test:
  secret_key_base: abef0f9f0706a0227383d176de90b62f74916ffa939444c2eb989d37d2123f0668707542d4e4fbe56620c1e8c668cc6d645a94f9a3200a518567f6da5f430a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
