# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab62fbb95c105b88a209154582aecd6041858bbf5e0b511e950455a9bdcfa87dca4fcabb7459194066079c0ebc8a71454daa1dcf70b935e58d9584ce81feab4a

test:
  secret_key_base: 2db650db7c0bbc8014a4ab155bca549f4325d4c9b0ab481697f095cc301205e36e7cf59da44c08f7523a071a92589aaeab96ff941c8a9c04d48a1969975c30cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
